export const ADD_CURRENT_ORG = 'ADD_CURRENT_ORG';
export const REMOVE_CURRENT_ORG = 'REMOVE_CURRENT_ORG';
export const ADD_NEW_ORG = 'ADD_NEW_ORG';
export const DELETE_ORG = 'DELETE_ORG';
export const INITIALIZE_ORGS = 'INITIALIZE_ORGS';
export const UPDATE_ORG = 'UPDATE_ORG'

export const ADD_CURRENT_EVENT = 'ADD_CURRENT_EVENT';
export const REMOVE_CURRENT_EVENT = 'REMOVE_CURRENT_EVENT';
export const ADD_NEW_EVENT = 'ADD_NEW_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const INITIALIZE_EVENTS = 'INITIALIZE_EVENTS';
export const UPDATE_EVENT = 'UPDATE_EVENT'

export const GET_ORGS_SAGA = 'GET_ORGS_SAGA';
export const GET_EVENTS_SAGA = 'GET_EVENTS_SAGA';

 
