export const ADD_CURRENT_ORG = 'ADD_CURRENT_ORG';
export const REMOVE_CURRENT_ORG = 'REMOVE_CURRENT_ORG';
export const ADD_NEW_ORG = 'ADD_NEW_ORG';
export const DELETE_ORG = 'DELETE_ORG';
export const INITIALIZE_ORGS = 'INITIALIZE_ORGS';
export const UPDATE_ORG = 'UPDATE_ORG'
export const INIT_ORGS_STATE = 'INIT_ORGS_STATE'
export const CLEAR_ORGS_STATE = 'CLEAR_ORGS_STATE'

export const ADD_CURRENT_EVENT = 'ADD_CURRENT_EVENT';
export const REMOVE_CURRENT_EVENT = 'REMOVE_CURRENT_EVENT';
export const ADD_NEW_EVENT = 'ADD_NEW_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const INITIALIZE_EVENTS = 'INITIALIZE_EVENTS';
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const INIT_EVENTS_STATE = 'INIT_EVENTS_STATE'
export const CLEAR_EVENTS_STATE = 'CLEAR_EVENTS_STATE'
